# Generated by Django 5.0.3 on 2024-03-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsevalue',
            old_name='FormResponse',
            new_name='form_response',
        ),
        migrations.AddField(
            model_name='responsevalue',
            name='value',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
    ]
