# Generated by Django 5.0.3 on 2024-03-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_formresponse_responsevalue_form_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='config',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='slug',
            field=models.CharField(default=1, max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
